"""first

Revision ID: 2b8a9cb511f8
Revises: 
Create Date: 2022-11-01 17:53:47.649086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b8a9cb511f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='farmer_table')
    op.drop_table('farmer_table')
    op.drop_index('id', table_name='movement_table')
    op.drop_table('movement_table')
    op.drop_index('id', table_name='credit_access_table')
    op.drop_table('credit_access_table')
    op.drop_index('id', table_name='capital_table')
    op.drop_table('capital_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BVN', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MainSourceofIncome', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OtherSourceofIncomeApartfromFarming', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NumberofPeopleProvidingRegularIncometohousehold', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DoyouhaveanAccountwithanyCommercialBank', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WhatisyourFirstOptionforgettingthenecessaryMoney', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WouldyouNeedaLoan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowManyMonthswillyouneedtopayback', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DidtheQtyofyourHarvestChange', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DidyourExpenseinpestontrolChange', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'capital_table', ['id'], unique=False)
    op.create_table('credit_access_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BVN', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HaveYouEverServedasTreasurerinyourGroup', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowManyMonthshaveyouServedinthisCapacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DoyoudoMonthlySavinginyourGroup', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IfYesHowMuchDoyouSetAsideMonthly', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HaveyouhaddifficultytopayupLoansontimeinthepast4years', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IfYesHowMuch', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('IfYesWhy', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowManyloanshaveyouhaddifficultytopaybackinthepast4years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HowManyloanshaveyouhaveyoupaidbackinthepast4years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HowManyHaveyouPaidOnOrBeforeduedate', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EstimateMonthlyincomeafterharvestandsalesofyourfarmproduce', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CostofCultivationinthisPlantingSeason', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HaveYouExchangedyourFarmProducetopayupforLoanstakeninthepast', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IfYesHowManytimesinthepast4years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('IfNoWhatOtherCollateralDoYouUseforLoansinthepast4years', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowmuchdoyouwantforALoan', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HowManyYearsHaveYoubeenCultivatingthisCrop', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('WhatisyourturnoverforAYear', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'credit_access_table', ['id'], unique=False)
    op.create_table('movement_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('to_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('movement_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'movement_table', ['id'], unique=False)
    op.create_table('farmer_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Surname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Telephone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Age', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Gender', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MaritalStatus', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('BVN', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MeansofID', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('YearofIssue', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ExpiryYear', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NIN', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PermanentAddress', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Landmark', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Stateoforigin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('LGA', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Group', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farmer_table', ['id'], unique=False)
    # ### end Alembic commands ###
