"""empty message

Revision ID: 426d7f16f721
Revises: 9fd452c65436
Create Date: 2023-02-01 08:46:58.689632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426d7f16f721'
down_revision = '9fd452c65436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'score_card', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_card', type_='unique')
    # ### end Alembic commands ###
