"""empty message

Revision ID: 9fd452c65436
Revises: 1a21a45854a7
Create Date: 2023-01-31 11:08:43.934388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd452c65436'
down_revision = '1a21a45854a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loantransfers', sa.Column('mobile', sa.String(length=200), nullable=True))
    op.add_column('score_card', sa.Column('mobile', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_card', 'mobile')
    op.drop_column('loantransfers', 'mobile')
    # ### end Alembic commands ###
