"""empty message

Revision ID: ddb58a074109
Revises: f724d5817624
Create Date: 2023-01-06 22:16:30.789422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb58a074109'
down_revision = 'f724d5817624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date_filled', table_name='crop_card')
    op.drop_index('fertilizer', table_name='crop_card')
    op.drop_index('fertilizer_cost', table_name='crop_card')
    op.drop_index('harvest', table_name='crop_card')
    op.drop_index('harvest_cost', table_name='crop_card')
    op.drop_index('labour', table_name='crop_card')
    op.drop_index('labour_cost', table_name='crop_card')
    op.drop_index('mechanization', table_name='crop_card')
    op.drop_index('mechanization_cost', table_name='crop_card')
    op.drop_index('other_cost', table_name='crop_card')
    op.drop_index('others', table_name='crop_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('others', 'crop_card', ['others'], unique=False)
    op.create_index('other_cost', 'crop_card', ['other_cost'], unique=False)
    op.create_index('mechanization_cost', 'crop_card', ['mechanization_cost'], unique=False)
    op.create_index('mechanization', 'crop_card', ['mechanization'], unique=False)
    op.create_index('labour_cost', 'crop_card', ['labour_cost'], unique=False)
    op.create_index('labour', 'crop_card', ['labour'], unique=False)
    op.create_index('harvest_cost', 'crop_card', ['harvest_cost'], unique=False)
    op.create_index('harvest', 'crop_card', ['harvest'], unique=False)
    op.create_index('fertilizer_cost', 'crop_card', ['fertilizer_cost'], unique=False)
    op.create_index('fertilizer', 'crop_card', ['fertilizer'], unique=False)
    op.create_index('date_filled', 'crop_card', ['date_filled'], unique=False)
    # ### end Alembic commands ###
