"""empty message

Revision ID: f116c2705a33
Revises: 5d38399c8bda
Create Date: 2023-01-06 15:40:54.357782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f116c2705a33'
down_revision = '5d38399c8bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('company', sa.String(length=200), nullable=True))
    op.add_column('loantransfers', sa.Column('company', sa.String(length=200), nullable=True))
    op.add_column('loantransfers', sa.Column('group', sa.String(length=200), nullable=True))
    op.drop_column('loantransfers', 'farmer_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loantransfers', sa.Column('farmer_name', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('loantransfers', 'group')
    op.drop_column('loantransfers', 'company')
    op.drop_column('loans', 'company')
    # ### end Alembic commands ###
