"""empty message

Revision ID: f724d5817624
Revises: a76aa0d02878
Create Date: 2023-01-06 21:45:06.884596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f724d5817624'
down_revision = 'a76aa0d02878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='score_history')
    op.drop_table('score_history')
    op.add_column('loantransfers', sa.Column('score', sa.String(length=200), nullable=True))
    op.add_column('loantransfers', sa.Column('bin', sa.String(length=200), nullable=True))
    op.add_column('score_card', sa.Column('applyLoanAmount', sa.String(length=200), nullable=True))
    op.add_column('score_card', sa.Column('term_months', sa.String(length=200), nullable=True))
    op.add_column('score_card', sa.Column('score', sa.String(length=200), nullable=True))
    op.add_column('score_card', sa.Column('bin', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_card', 'bin')
    op.drop_column('score_card', 'score')
    op.drop_column('score_card', 'term_months')
    op.drop_column('score_card', 'applyLoanAmount')
    op.drop_column('loantransfers', 'bin')
    op.drop_column('loantransfers', 'score')
    op.create_table('score_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('number_of_land', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('owner_caretaker', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('crop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('intercropping', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('machines', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('estimate_monthly_income', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('years_cultivating', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('owns_a_bank_account', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('size_of_farm', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('number_of_crops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_in_a_cooperative', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_agronomist_visits', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('applyLoanAmount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('term_months', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('score', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('date_created', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'score_history', ['id'], unique=False)
    # ### end Alembic commands ###
