"""empty message

Revision ID: 47a5b9574cd4
Revises: 9de999c5430f
Create Date: 2022-11-15 09:28:44.692044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47a5b9574cd4'
down_revision = '9de999c5430f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='credit_access_table')
    op.drop_table('credit_access_table')
    op.drop_table('loans')
    op.drop_index('id', table_name='movement_table')
    op.drop_table('movement_table')
    op.drop_index('id', table_name='conditions_table')
    op.drop_table('conditions_table')
    op.drop_index('id', table_name='agronomy_services_table')
    op.drop_table('agronomy_services_table')
    op.drop_index('id', table_name='capital_table')
    op.drop_table('capital_table')
    op.drop_index('id', table_name='farmland_table')
    op.drop_table('farmland_table')
    op.drop_index('Bvn', table_name='score_card')
    op.drop_index('id', table_name='score_card')
    op.drop_table('score_card')
    op.drop_index('id', table_name='cultivation_table')
    op.drop_table('cultivation_table')
    op.drop_table('crop')
    op.drop_table('locations')
    op.drop_index('id', table_name='harvest_table')
    op.drop_table('harvest_table')
    op.drop_index('id', table_name='mechanization_table')
    op.drop_table('mechanization_table')
    op.drop_index('id', table_name='psychometrics_table')
    op.drop_table('psychometrics_table')
    op.drop_index('id', table_name='mobile_data_table')
    op.drop_table('mobile_data_table')
    op.drop_index('id', table_name='credit_history_table')
    op.drop_table('credit_history_table')
    op.drop_table('loantransfers')
    op.drop_table('crops')
    op.drop_index('id', table_name='farmer_table')
    op.drop_table('farmer_table')
    op.drop_table('products')
    op.drop_index('id', table_name='capacity_table')
    op.drop_table('capacity_table')
    op.drop_index('id', table_name='productivity_viability_table')
    op.drop_table('productivity_viability_table')
    op.drop_index('id', table_name='farm_practice_table')
    op.drop_table('farm_practice_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_practice_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SizeOfFarm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FarmIsRentedorLeased', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfYearsLeased', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('UsesMachines', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RotatesCrops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfHectaresProducedYearly', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ApproxFertilizerUse', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfFertlizerApplications', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DecisionForSpraying', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WeedControlPractice', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EstimatedIncomePerCrop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropthatcanSellWell', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasFarmPlanOrProject', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmProjectInfo', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farm_practice_table', ['id'], unique=False)
    op.create_table('productivity_viability_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CropsCultivated', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('GrowsCrops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OilPalmFertilizers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CocoaFertilizers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FertilizerFrequency', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PestFungHerbicides', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('StageChemicalApplied', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfOilDrums', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfBagsSesame', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfBagsSoyaBeans', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfBagsMaize', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfBagsSorghum', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfBagsCocoaBeans', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CropTrainedOn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WhereWhenWhoTrained', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfTraining', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PruningFrequency', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropBasedProblems', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('TooYoungCrops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('YoungCropsAndStage', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CultivationStartdate', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsIntensiveFarmingPractised', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EconomicActivities', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'productivity_viability_table', ['id'], unique=False)
    op.create_table('capacity_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HowLongBeenFarming', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ParticipatedInTraining', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmingPractice', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('KeepsAnimals', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasCooperative', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CooperativeName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EducationLevel', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'capacity_table', ['id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('farmer_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Surname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Telephone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Age', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Gender', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MaritalStatus', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MeansofID', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('YearofIssue', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ExpiryYear', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Nin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PermanentAddress', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Landmark', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Stateoforigin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Lga', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Group', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farmer_table', ['id'], unique=False)
    op.create_table('crops',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crop_name', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('variety', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('farmer_name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('bvn', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cost_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selling_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loantransfers',
    sa.Column('transfer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loan_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_farmer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('transfer_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('transfer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('credit_history_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('HasTakenLoanBefore', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SourceOfLoan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PastLoanAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HowLoanWasRepaid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('IsReadyToPayInterest', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CanProvideCollateral', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WhyNoCollateral', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'credit_history_table', ['id'], unique=False)
    op.create_table('mobile_data_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MobilePhoneType', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Avweeklyphoneuse', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Callsoutnumber', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Callsoutminutes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Callsinnumber', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Callinminutes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SMSsent', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Dataprecedingplanswitch', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Billpaymenthistory', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Avweeklydatarefill', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfmobileapps', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AvTimeSpentOnApp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MobileAppKinds', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AppDeleteRate', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'mobile_data_table', ['id'], unique=False)
    op.create_table('psychometrics_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FluidIntelligence', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AttitudesandBeliefs', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AgribusinessSkills', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EthicsandHonesty', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SavesEnough', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasLazyNeighbors', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'psychometrics_table', ['id'], unique=False)
    op.create_table('mechanization_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MachinesUsed', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MachineHasHelped', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AdviseMachineOrLabour', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OtherMachinesNeeded', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CanAcquireMoreLands', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PercentCostSaved', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'mechanization_table', ['id'], unique=False)
    op.create_table('harvest_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('when_is_harvest_season', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_hired_workers', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_of_family_workers', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_of_permanent_workers', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_hired_constantly', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'harvest_table', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('crop',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crop_name', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('variety', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('farmer_name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('bvn', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cost_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selling_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cultivation_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_of_labor', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pay_for_labor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('how_many_housechildren_help', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('season_children_help', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('labor_children_do', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('household_vs_hire_cost', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('labor_women_do', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('percent_female_hired', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'cultivation_table', ['id'], unique=False)
    op.create_table('score_card',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('number_of_land', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('owner_caretaker', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('crop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('intercropping', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('machines', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('estimate_monthly_income', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('years_cultivating', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('apply_loan_amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('owns_a_bank_account', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('size_of_farm', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('grows_more_than_one_crop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_in_a_cooperative', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_agronomist_visits', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'score_card', ['id'], unique=False)
    op.create_index('Bvn', 'score_card', ['Bvn'], unique=False)
    op.create_table('farmland_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfFarmlands', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OwnerOrCaretaker', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmOwnerName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmOwnerPhoneNo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RelationshipWithOwner', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('InheritedFrom', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SizeOfFarm', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmCoordinates', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmAddress', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('KeepsAnimals', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AnimalsFeedOn', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farmland_table', ['id'], unique=False)
    op.create_table('capital_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MainIncomeSource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OtherIncomeSource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfIncomeEarners', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HasBankAccount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FirstFundingOption', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NeedsALoan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PayBackMonths', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HarvestQtyChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PestExpenseChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'capital_table', ['id'], unique=False)
    op.create_table('agronomy_services_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('KnowsAgriProcessed', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AgronomistThatTrainedYou', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CanManageEcosystem', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowToManageEcosystem', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsTrainingBeneficial', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FieldRoutines', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HarvestingChanges', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsCropCalendarBeneficial', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropCalendarBenefits', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RecordKeepingBenefits', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'agronomy_services_table', ['id'], unique=False)
    op.create_table('conditions_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LengthOfHarvestChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'conditions_table', ['id'], unique=False)
    op.create_table('movement_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('from_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('to_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('movement_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'movement_table', ['id'], unique=False)
    op.create_table('loans',
    sa.Column('loan_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('loan_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('credit_access_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Bvn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HasServedAsTreasurer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DurationAsTreasurer', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SavesMoneyMonthly', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SavingsAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HadDifficultyRepaying', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DifficultLoanAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DifficultyReason', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfDifficultLoans', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfRepaidLoans', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfLoansOnTime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EstMonthlyIncome', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CostOfCultivation', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FarmProduceExchanged', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfTimesExchanged', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Collateral', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ApplyLoanAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('YearsOfCultivating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AnnualTurnover', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'credit_access_table', ['id'], unique=False)
    # ### end Alembic commands ###
