"""empty message

Revision ID: 5491d2dce25a
Revises: 96e190e23049
Create Date: 2022-11-23 07:46:49.693753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5491d2dce25a'
down_revision = '96e190e23049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('repayment_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'repayment_months')
    # ### end Alembic commands ###
