"""empty message

Revision ID: 5d38399c8bda
Revises: 6666df357493
Create Date: 2023-01-04 13:02:35.552129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d38399c8bda'
down_revision = '6666df357493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('loans', sa.Column('type', sa.String(length=200), nullable=True))
    #op.drop_index('loan_type', table_name='loans')
    
    #op.drop_column('loans', 'loan_type')
    #op.add_column('loantransfers', sa.Column('type', sa.String(length=200), nullable=True))
    #op.drop_column('loantransfers', 'loan_type')
    op.alter_column('loans',
                     column_name='loan_type',
                     new_column_name='type',
                     existing_type='String200',
                     existing_nullable=True)
    op.alter_column('loantransfers',
                     column_name='loan_type',
                     new_column_name='type',
                     existing_type='String200',
                     existing_nullable=True)
    op.create_unique_constraint(None, 'loans', ['type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loantransfers', sa.Column('loan_type', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('loantransfers', 'type')
    op.add_column('loans', sa.Column('loan_type', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'loans', type_='unique')
    op.create_index('loan_type', 'loans', ['loan_type'], unique=False)
    op.drop_column('loans', 'type')
    # ### end Alembic commands ###
