"""empty message

Revision ID: 6666df357493
Revises: f3f5543357a6
Create Date: 2023-01-04 12:39:52.161200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6666df357493'
down_revision = 'f3f5543357a6'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column('safety_table', 'Wear')
    op.drop_column('safety_table', 'FermentDays')
    op.drop_column('safety_table', 'AgroChemSource')
    op.drop_column('safety_table', 'HerbicideStore')
    op.drop_column('safety_table', 'DoWithBroken')
    op.drop_column('safety_table', 'FFBStore')
    op.drop_column('safety_table', 'FermentReason')
    op.drop_column('safety_table', 'HarvestTool')
    op.drop_column('safety_table', 'BrokenQty')
    op.drop_column('safety_table', 'UnripeQty')
    op.drop_column('safety_table', 'DoWithUnripe')
    op.drop_column('safety_table', 'Ferment')
    op.drop_column('safety_table', 'Disposal')
    op.drop_column('safety_table', 'CocoaStore')
    op.drop_column('safety_table', 'Herbicide')
    op.drop_column('score_analytics', 'Scores')
    op.drop_column('score_analytics', 'Collateral')
    op.drop_column('score_analytics', 'Capital')
    op.drop_column('score_analytics', 'Character')
    op.drop_column('score_analytics', 'Conditions')
    op.drop_column('score_analytics', 'Capacity')
    op.drop_column('agronomy_services_table', 'AgronomistThatTrainedYou')
    op.drop_column('agronomy_services_table', 'IsTrainingBeneficial')
    op.drop_column('agronomy_services_table', 'FieldRoutines')
    op.drop_column('agronomy_services_table', 'IsCropCalendarBeneficial')
    op.drop_column('agronomy_services_table', 'CropCalendarBenefits')
    op.drop_column('agronomy_services_table', 'HarvestingChanges')
    op.drop_column('agronomy_services_table', 'HowToManageEcosystem')
    op.drop_column('agronomy_services_table', 'KnowsAgriProcessed')
    op.drop_column('agronomy_services_table', 'CanManageEcosystem')
    op.drop_column('agronomy_services_table', 'RecordKeepingBenefits')
    op.drop_column('capacity_table', 'KeepsAnimals')
    op.drop_column('capacity_table', 'HowLongBeenFarming')
    op.drop_column('capacity_table', 'ParticipatedInTraining')
    op.drop_column('capacity_table', 'FarmingPractice')
    op.drop_column('capacity_table', 'CooperativeName')
    op.drop_column('capacity_table', 'EducationLevel')
    op.drop_column('capacity_table', 'HasCooperative')

    op.drop_column('capital_table', 'NeedsALoan')
    op.drop_column('capital_table', 'HasBankAccount')
    op.drop_column('capital_table', 'HarvestQtyChanged')
    op.drop_column('capital_table', 'MainIncomeSource')
    op.drop_column('capital_table', 'PestExpenseChanged')
    op.drop_column('capital_table', 'NoOfIncomeEarners')
    op.drop_column('capital_table', 'PayBackMonths')
    op.drop_column('capital_table', 'FirstFundingOption')
    op.drop_column('capital_table', 'OtherIncomeSource')

    op.drop_column('care_table', 'Affordable')
    op.drop_column('care_table', 'Qualification')
    op.drop_column('care_table', 'FarmDistance')
    op.drop_column('care_table', 'InSchool')
    op.drop_column('care_table', 'HealthCentCount')
    op.drop_column('care_table', 'HealthCentLoc')
    op.drop_column('care_table', 'HealthCentFunctional')
    op.drop_column('care_table', 'SchoolFunctional')
    op.drop_column('care_table', 'StudyTime')
    op.drop_column('care_table', 'LastCheck')
    op.drop_column('care_table', 'AltIncomeSource')
    op.drop_column('care_table', 'SchoolCount')
    op.drop_column('care_table', 'StudyWhere')
    op.drop_column('care_table', 'Level')
    op.drop_column('care_table', 'FirstAid')
    op.drop_column('care_table', 'InjuryEvent')
    op.drop_column('care_table', 'HealthCentDistance')
    op.drop_column('credit_history_table', 'IsReadyToPayInterest')
    op.drop_column('credit_history_table', 'SourceOfLoan')
    op.drop_column('credit_history_table', 'PastLoanAmount')
    op.drop_column('credit_history_table', 'HasTakenLoanBefore')
    op.drop_column('credit_history_table', 'HowLoanWasRepaid')
    op.drop_column('credit_history_table', 'WhyNoCollateral')
    op.drop_column('credit_history_table', 'CanProvideCollateral')
    op.drop_column('credit_access_table', 'YearsOfCultivating')
    op.drop_column('credit_access_table', 'HadDifficultyRepaying')
    op.drop_column('credit_access_table', 'CostOfCultivation')
    op.drop_column('credit_access_table', 'AnnualTurnover')
    op.drop_column('credit_access_table', 'NoOfLoansOnTime')
    op.drop_column('credit_access_table', 'SavesMoneyMonthly')
    op.drop_column('credit_access_table', 'Collateral')
    op.drop_column('credit_access_table', 'NoOfDifficultLoans')
    op.drop_column('credit_access_table', 'DurationAsTreasurer')
    op.drop_column('credit_access_table', 'FarmProduceExchanged')
    op.drop_column('credit_access_table', 'NoOfTimesExchanged')
    op.drop_column('credit_access_table', 'HasServedAsTreasurer')
    op.drop_column('credit_access_table', 'DifficultLoanAmount')
    op.drop_column('credit_access_table', 'SavingsAmount')
    op.drop_column('credit_access_table', 'NoOfRepaidLoans')
    op.drop_column('credit_access_table', 'EstMonthlyIncome')
    op.drop_column('credit_access_table', 'DifficultyReason')
    op.drop_column('credit_access_table', 'ApplyLoanAmount')
    op.drop_column('farm_practice_table', 'SizeOfFarm')
    op.drop_column('farm_practice_table', 'EstimatedIncomePerCrop')
    op.drop_column('farm_practice_table', 'FarmProjectInfo')
    op.drop_column('farm_practice_table', 'FarmIsRentedorLeased')
    op.drop_column('farm_practice_table', 'DecisionForSpraying')
    op.drop_column('farm_practice_table', 'HasFarmPlanOrProject')
    op.drop_column('farm_practice_table', 'NoOfFertlizerApplications')
    op.drop_column('farm_practice_table', 'RotatesCrops')
    op.drop_column('farm_practice_table', 'NoOfYearsLeased')
    op.drop_column('farm_practice_table', 'WeedControlPractice')
    op.drop_column('farm_practice_table', 'CropthatcanSellWell')
    op.drop_column('farm_practice_table', 'NoOfHectaresProducedYearly')
    op.drop_column('farm_practice_table', 'UsesMachines')
    op.drop_column('farm_practice_table', 'ApproxFertilizerUse')
    op.create_unique_constraint(None, 'farmer_table', ['bvn'])
    op.drop_column('conditions_table', 'CropYieldPrediction')
    op.drop_column('conditions_table', 'CropExpectedMarketValue')
    op.drop_column('conditions_table', 'ZowaselMarketplacePriceOffers')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('living_table', 'Position')
    op.drop_column('living_table', 'StaysWithFamily')
    op.drop_column('living_table', 'Typeoftoilet')
    op.drop_column('living_table', 'MaleUnderAge')
    op.drop_column('living_table', 'HouseOwned')
    op.drop_column('living_table', 'SourceOfWater')
    op.drop_column('living_table', 'Input')
    op.drop_column('living_table', 'PowerPayment')
    op.drop_column('living_table', 'SourceEverytime')
    op.drop_column('living_table', 'HasGroup')
    op.drop_column('living_table', 'OwnOtherLands')
    op.drop_column('living_table', 'ChildrenAboveAge')
    op.drop_column('living_table', 'MaleAboveAge')
    op.drop_column('living_table', 'ChildrenUnderAge')
    op.drop_column('living_table', 'CookingMethod')
    op.drop_column('living_table', 'FemaleUnderAge')
    op.drop_column('living_table', 'HaveElectricity')
    op.drop_column('living_table', 'RelationshipWithOwner')
    op.drop_column('living_table', 'FemaleAboveAge')
    op.drop_column('living_table', 'HouseHoldEats')
    op.drop_column('living_table', 'HasAccessedInput')
    op.drop_column('living_table', 'LivesWith')
    op.drop_column('living_table', 'KitchenSink')
    op.drop_column('living_table', 'StandardofLiving')
    op.drop_column('mechanization_table', 'MachinesUsed')
    op.drop_column('mechanization_table', 'AdviseMachineOrLabour')
    op.drop_column('mechanization_table', 'PercentCostSaved')
    op.drop_column('mechanization_table', 'CanAcquireMoreLands')
    op.drop_column('mechanization_table', 'OtherMachinesNeeded')
    op.drop_column('mechanization_table', 'MachineHasHelped')
    op.drop_column('inputs_info', 'Seeds')
    op.drop_column('inputs_info', 'Insecticides')
    op.drop_column('inputs_info', 'Fungicides')
    op.drop_column('inputs_info', 'Fertilizers')
    op.drop_column('inputs_info', 'Herbicides')
    op.drop_column('farmland_table', 'SizeOfFarm')
    op.drop_column('farmland_table', 'KeepsAnimals')
    op.drop_column('farmland_table', 'RelationshipWithOwner')
    op.drop_column('farmland_table', 'AnimalsFeedOn')
    op.drop_column('farmland_table', 'FarmOwnerName')
    op.drop_column('farmland_table', 'FarmOwnerPhoneNo')
    op.drop_column('farmland_table', 'OwnerOrCaretaker')
    op.drop_column('farmland_table', 'InheritedFrom')
    op.drop_column('farmland_table', 'FarmCoordinates')
    op.drop_column('farmland_table', 'NoOfFarmlands')
    op.drop_column('farmland_table', 'FarmAddress')
    op.drop_column('mobile_data_table', 'Billpaymenthistory')
    op.drop_column('mobile_data_table', 'AppDeleteRate')
    op.drop_column('mobile_data_table', 'Callinminutes')
    op.drop_column('mobile_data_table', 'SMSsent')
    op.drop_column('mobile_data_table', 'Callsinnumber')
    op.drop_column('mobile_data_table', 'Avweeklyphoneuse')
    op.drop_column('mobile_data_table', 'Callsoutnumber')
    op.drop_column('mobile_data_table', 'Callsoutminutes')
    op.drop_column('mobile_data_table', 'Dataprecedingplanswitch')
    op.drop_column('mobile_data_table', 'NoOfmobileapps')
    op.drop_column('mobile_data_table', 'MobileAppKinds')
    op.drop_column('mobile_data_table', 'MobilePhoneType')
    op.drop_column('mobile_data_table', 'AvTimeSpentOnApp')
    op.drop_column('mobile_data_table', 'Avweeklydatarefill')
    op.drop_column('planet_table', 'WasteMgt')
    op.drop_column('planet_table', 'EnergySource')
    op.drop_column('planet_table', 'Measures')
    op.drop_column('planet_table', 'GreyWater')
    op.drop_column('planet_table', 'ReplacedTree')
    op.drop_column('planet_table', 'SourceOfWater')
    op.drop_column('planet_table', 'RaiseOrBuy')
    op.drop_column('planet_table', 'Pollution')
    op.drop_column('planet_table', 'DegradedLand')
    op.drop_column('planet_table', 'Mill')
    op.drop_column('planet_table', 'Season')
    op.drop_column('planet_table', 'CropIntercropped')
    op.drop_column('planet_table', 'RecycleWaste')
    op.drop_column('planet_table', 'RecycleGreyWater')
    op.drop_column('planet_table', 'CropRotation')
    op.drop_column('planet_table', 'WasteDisposal')
    op.drop_column('planet_table', 'Burning')
    op.drop_column('planet_table', 'PollutionFreq')
    op.drop_column('planet_table', 'WhenSuffered')
    op.drop_column('planet_table', 'Suffered')
    op.drop_column('planet_table', 'Variety')
    op.drop_column('planet_table', 'Crop')
    op.drop_column('planet_table', 'Placement')
    op.drop_column('planet_table', 'BuyWhere')
    op.drop_column('planet_table', 'Disaster')
    op.drop_column('planet_table', 'CoverCrops')
    op.drop_column('planet_table', 'PlanToExpand')
    op.drop_column('planet_table', 'QtyBought')
    op.drop_column('planet_table', 'Intercrop')
    op.drop_column('planet_table', 'SeedlingPrice')
    op.drop_column('productivity_viability_table', 'EconomicActivities')
    op.drop_column('productivity_viability_table', 'NoOfBagsMaize')
    op.drop_column('productivity_viability_table', 'IsIntensiveFarmingPractised')
    op.drop_column('productivity_viability_table', 'CropTrainedOn')
    op.drop_column('productivity_viability_table', 'WhereWhenWhoTrained')
    op.drop_column('productivity_viability_table', 'PruningFrequency')
    op.drop_column('productivity_viability_table', 'YoungCropsAndStage')
    op.drop_column('productivity_viability_table', 'NoOfBagsCocoaBeans')
    op.drop_column('productivity_viability_table', 'NoOfTraining')
    op.drop_column('productivity_viability_table', 'NoOfBagsSorghum')
    op.drop_column('productivity_viability_table', 'PestFungHerbicides')
    op.drop_column('productivity_viability_table', 'NoOfBagsSesame')
    op.drop_column('productivity_viability_table', 'CropBasedProblems')
    op.drop_column('productivity_viability_table', 'NoOfOilDrums')
    op.drop_column('productivity_viability_table', 'CropsCultivated')
    op.drop_column('productivity_viability_table', 'CultivationStartdate')
    op.drop_column('productivity_viability_table', 'CocoaFertilizers')
    op.drop_column('productivity_viability_table', 'GrowsCrops')
    op.drop_column('productivity_viability_table', 'FertilizerFrequency')
    op.drop_column('productivity_viability_table', 'NoOfBagsSoyaBeans')
    op.drop_column('productivity_viability_table', 'StageChemicalApplied')
    op.drop_column('productivity_viability_table', 'OilPalmFertilizers')
    op.drop_column('productivity_viability_table', 'TooYoungCrops')
    
    op.drop_column('psychometrics_table', 'AgribusinessSkills')
    op.drop_column('psychometrics_table', 'EthicsandHonesty')
    op.drop_column('psychometrics_table', 'SavesEnough')
    op.drop_column('psychometrics_table', 'AttitudesandBeliefs')
    op.drop_column('psychometrics_table', 'HasLazyNeighbors')
    op.drop_column('psychometrics_table', 'FluidIntelligence')
    
    op.add_column('agronomy_services_table', sa.Column('knowsagriprocessed', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('agronomistthattrainedyou', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('canmanageecosystem', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('howtomanageecosystem', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('istrainingbeneficial', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('fieldroutines', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('harvestingchanges', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('iscropcalendarbeneficial', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('cropcalendarbenefits', sa.String(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('recordkeepingbenefits', sa.String(length=200), nullable=True))
    
    op.add_column('capacity_table', sa.Column('howlongbeenfarming', sa.String(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('participatedintraining', sa.String(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('farmingpractice', sa.String(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('keepsanimals', sa.String(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('hascooperative', sa.String(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('cooperativename', sa.String(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('educationlevel', sa.String(length=200), nullable=True))
    
    op.add_column('capital_table', sa.Column('mainincomesource', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('otherincomesource', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('noofincomeearners', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('hasbankaccount', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('firstfundingoption', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('needsaloan', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('paybackmonths', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('harvestqtychanged', sa.String(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('pestexpensechanged', sa.String(length=200), nullable=True))
    
    op.add_column('care_table', sa.Column('healthcentloc', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('healthcentcount', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('healthcentdistance', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('healthcentfunctional', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('affordable', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('farmdistance', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('injuryevent', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('firstaid', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('lastcheck', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('inschool', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('level', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('schoolcount', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('schoolfunctional', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('qualification', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('studytime', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('studywhere', sa.String(length=200), nullable=True))
    op.add_column('care_table', sa.Column('altIncomesource', sa.String(length=200), nullable=True))
    
    op.add_column('conditions_table', sa.Column('cropyieldprediction', sa.String(length=200), nullable=True))
    op.add_column('conditions_table', sa.Column('cropexpectedmarketvalue', sa.String(length=200), nullable=True))
    op.add_column('conditions_table', sa.Column('zowaselmarketplacepriceoffers', sa.String(length=200), nullable=True))
    
    op.add_column('credit_access_table', sa.Column('hasservedastreasurer', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('durationastreasurer', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('savesmoneymonthly', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('savingsamount', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('haddifficultyrepaying', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('difficultloanamount', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('difficultyreason', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('noofdifficultloans', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('noofrepaidloans', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('noofloansontime', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('estmonthlyincome', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('costofcultivation', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('farmproduceexchanged', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('nooftimesexchanged', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('collateral', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('applyloanamount', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('yearsofcultivating', sa.String(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('annualturnover', sa.String(length=200), nullable=True))
    
    op.add_column('credit_history_table', sa.Column('hastakenloanbefore', sa.String(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('sourceofloan', sa.String(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('pastloanamount', sa.String(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('howloanwasrepaid', sa.String(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('isreadytopayinterest', sa.String(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('canprovidecollateral', sa.String(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('whynocollateral', sa.String(length=200), nullable=True))
    
    op.add_column('farm_practice_table', sa.Column('sizeoffarm', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('farmisrentedorleased', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('noofyearsleased', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('usesmachines', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('rotatescrops', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('noOfhectaresproducedyearly', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('approxfertilizeruse', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('nooffertlizerapplications', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('decisionforspraying', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('weedcontrolpractice', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('estimatedincomepercrop', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('cropthatcansellwell', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('hasfarmplanorproject', sa.String(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('farmprojectinfo', sa.String(length=200), nullable=True))
    
    op.add_column('farmland_table', sa.Column('nooffarmlands', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('ownerorcaretaker', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('farmownername', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('farmownerphoneno', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('relationshipwithowner', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('inheritedfrom', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('sizeoffarm', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('farmcoordinates', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('farmaddress', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('keepsanimals', sa.String(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('animalsfeedon', sa.String(length=200), nullable=True))
    
    op.add_column('inputs_info', sa.Column('fertilizers', sa.String(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('herbicides', sa.String(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('fungicides', sa.String(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('insecticides', sa.String(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('seeds', sa.String(length=200), nullable=True))
    
    op.add_column('living_table', sa.Column('houseowned', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('stayswithfamily', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('relationshipwithowner', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('householdeats', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('maleunderage', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('femaleunderage', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('childrenunderage', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('maleaboveage', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('femaleaboveage', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('childrenaboveage', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('liveswith', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('ownotherlands', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('standardofliving', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('sourceofwater', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('sourceeverytime', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('cookingmethod', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('haveelectricity', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('powerpayment', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('typeoftoilet', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('kitchensink', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('hasgroup', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('position', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('hasaccessedInput', sa.String(length=200), nullable=True))
    op.add_column('living_table', sa.Column('input', sa.String(length=200), nullable=True))
    
    op.create_unique_constraint(None, 'loantransfers', ['id'])
    op.add_column('mechanization_table', sa.Column('machinesused', sa.String(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('machinehashelped', sa.String(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('advisemachineorlabour', sa.String(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('othermachinesneeded', sa.String(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('canacquiremorelands', sa.String(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('percentcostsaved', sa.String(length=200), nullable=True))
    
    op.add_column('mobile_data_table', sa.Column('mobilephonetype', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('avweeklyphoneuse', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('callsoutnumber', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('callsoutminutes', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('callsinnumber', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('callinminutes', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('smssent', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('dataprecedingplanswitch', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('billpaymenthistory', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('avweeklydatarefill', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('noOfmobileapps', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('avtimespentonapp', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('mobileappkinds', sa.String(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('appdeleterate', sa.String(length=200), nullable=True))
    
    op.add_column('planet_table', sa.Column('plantoexpand', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('crop', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('variety', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('raiseorbuy', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('buywhere', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('seedlingprice', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('qtybought', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('degradedland', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('croprotation', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('season', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('disaster', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('burning', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('mill', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('energysource', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('replacedtree', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('placement', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('sourceofwater', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('covercrops', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('intercrop', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('cropintercropped', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('wastemgt', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('wastedisposal', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('recyclewaste', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('suffered', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('whensuffered', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('greywater', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('recyclegreywater', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('pollution', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('pollutionfreq', sa.String(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('measures', sa.String(length=200), nullable=True))
    
    op.add_column('productivity_viability_table', sa.Column('cropscultivated', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('growscrops', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('oilpalmfertilizers', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('cocoafertilizers', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('fertilizerfrequency', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('pestfungherbicides', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('stagechemicalapplied', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('noofoildrums', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('noofbagssesame', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('noofbagssoyabeans', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('noofbagsmaize', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('noofbagssorghum', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('noofbagscocoabeans', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('croptrainedon', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('wherewhenwhotrained', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('nooftraining', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('pruningfrequency', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('cropbasedproblems', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('tooyoungcrops', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('youngcropsandstage', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('cultivationstartdate', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('isintensivefarmingpractised', sa.String(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('economicactivities', sa.String(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('fluidintelligence', sa.String(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('attitudesandbeliefs', sa.String(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('agribusinessskills', sa.String(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('ethicsandhonesty', sa.String(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('savesenough', sa.String(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('haslazyneighbors', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('ferment', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('fermentdays', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('fermentreason', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('brokenqty', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('dowithbroken', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('unripeqty', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('dowithunripe', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('cocoastore', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('ffbstore', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('herbicide', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('herbicidestore', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('agrochemsource', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('harvesttool', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('wear', sa.String(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('disposal', sa.String(length=200), nullable=True))
    
    op.add_column('score_analytics', sa.Column('scores', sa.String(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('conditions', sa.String(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('capital', sa.String(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('collateral', sa.String(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('capacity', sa.String(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('character', sa.String(length=200), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_analytics', sa.Column('Capacity', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('Conditions', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('Character', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('Capital', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('Collateral', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('score_analytics', sa.Column('Scores', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('score_analytics', 'character')
    op.drop_column('score_analytics', 'capacity')
    op.drop_column('score_analytics', 'collateral')
    op.drop_column('score_analytics', 'capital')
    op.drop_column('score_analytics', 'conditions')
    op.drop_column('score_analytics', 'scores')
    op.add_column('safety_table', sa.Column('Herbicide', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('CocoaStore', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('Disposal', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('Ferment', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('DoWithUnripe', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('UnripeQty', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('BrokenQty', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('HarvestTool', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('FermentReason', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('FFBStore', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('DoWithBroken', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('HerbicideStore', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('AgroChemSource', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('FermentDays', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('safety_table', sa.Column('Wear', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('safety_table', 'disposal')
    op.drop_column('safety_table', 'wear')
    op.drop_column('safety_table', 'harvesttool')
    op.drop_column('safety_table', 'agrochemsource')
    op.drop_column('safety_table', 'herbicidestore')
    op.drop_column('safety_table', 'herbicide')
    op.drop_column('safety_table', 'ffbstore')
    op.drop_column('safety_table', 'cocoastore')
    op.drop_column('safety_table', 'dowithunripe')
    op.drop_column('safety_table', 'unripeqty')
    op.drop_column('safety_table', 'dowithbroken')
    op.drop_column('safety_table', 'brokenqty')
    op.drop_column('safety_table', 'fermentreason')
    op.drop_column('safety_table', 'fermentdays')
    op.drop_column('safety_table', 'ferment')
    op.add_column('psychometrics_table', sa.Column('FluidIntelligence', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('HasLazyNeighbors', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('AttitudesandBeliefs', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('SavesEnough', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('EthicsandHonesty', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('psychometrics_table', sa.Column('AgribusinessSkills', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('psychometrics_table', 'haslazyneighbors')
    op.drop_column('psychometrics_table', 'savesenough')
    op.drop_column('psychometrics_table', 'ethicsandhonesty')
    op.drop_column('psychometrics_table', 'agribusinessskills')
    op.drop_column('psychometrics_table', 'attitudesandbeliefs')
    op.drop_column('psychometrics_table', 'fluidintelligence')
    op.add_column('productivity_viability_table', sa.Column('TooYoungCrops', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('OilPalmFertilizers', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('StageChemicalApplied', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('NoOfBagsSoyaBeans', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('FertilizerFrequency', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('GrowsCrops', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('CocoaFertilizers', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('CultivationStartdate', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('CropsCultivated', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('NoOfOilDrums', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('CropBasedProblems', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('NoOfBagsSesame', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('PestFungHerbicides', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('NoOfBagsSorghum', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('NoOfTraining', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('NoOfBagsCocoaBeans', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('YoungCropsAndStage', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('PruningFrequency', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('WhereWhenWhoTrained', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('CropTrainedOn', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('IsIntensiveFarmingPractised', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('NoOfBagsMaize', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('productivity_viability_table', sa.Column('EconomicActivities', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('productivity_viability_table', 'economicactivities')
    op.drop_column('productivity_viability_table', 'isintensivefarmingpractised')
    op.drop_column('productivity_viability_table', 'cultivationstartdate')
    op.drop_column('productivity_viability_table', 'youngcropsandstage')
    op.drop_column('productivity_viability_table', 'tooyoungcrops')
    op.drop_column('productivity_viability_table', 'cropbasedproblems')
    op.drop_column('productivity_viability_table', 'pruningfrequency')
    op.drop_column('productivity_viability_table', 'nooftraining')
    op.drop_column('productivity_viability_table', 'wherewhenwhotrained')
    op.drop_column('productivity_viability_table', 'croptrainedon')
    op.drop_column('productivity_viability_table', 'noofbagscocoabeans')
    op.drop_column('productivity_viability_table', 'noofbagssorghum')
    op.drop_column('productivity_viability_table', 'noofbagsmaize')
    op.drop_column('productivity_viability_table', 'noofbagssoyabeans')
    op.drop_column('productivity_viability_table', 'noofbagssesame')
    op.drop_column('productivity_viability_table', 'noofoildrums')
    op.drop_column('productivity_viability_table', 'stagechemicalapplied')
    op.drop_column('productivity_viability_table', 'pestfungherbicides')
    op.drop_column('productivity_viability_table', 'fertilizerfrequency')
    op.drop_column('productivity_viability_table', 'cocoafertilizers')
    op.drop_column('productivity_viability_table', 'oilpalmfertilizers')
    op.drop_column('productivity_viability_table', 'growscrops')
    op.drop_column('productivity_viability_table', 'cropscultivated')
    op.add_column('planet_table', sa.Column('SeedlingPrice', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Intercrop', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('QtyBought', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('PlanToExpand', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('CoverCrops', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Disaster', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('BuyWhere', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Placement', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Crop', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Variety', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Suffered', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('WhenSuffered', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('PollutionFreq', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Burning', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('WasteDisposal', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('CropRotation', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('RecycleGreyWater', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('RecycleWaste', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('CropIntercropped', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Season', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Mill', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('DegradedLand', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Pollution', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('RaiseOrBuy', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('SourceOfWater', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('ReplacedTree', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('GreyWater', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('Measures', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('EnergySource', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('planet_table', sa.Column('WasteMgt', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('planet_table', 'measures')
    op.drop_column('planet_table', 'pollutionfreq')
    op.drop_column('planet_table', 'pollution')
    op.drop_column('planet_table', 'recyclegreywater')
    op.drop_column('planet_table', 'greywater')
    op.drop_column('planet_table', 'whensuffered')
    op.drop_column('planet_table', 'suffered')
    op.drop_column('planet_table', 'recyclewaste')
    op.drop_column('planet_table', 'wastedisposal')
    op.drop_column('planet_table', 'wastemgt')
    op.drop_column('planet_table', 'cropintercropped')
    op.drop_column('planet_table', 'intercrop')
    op.drop_column('planet_table', 'covercrops')
    op.drop_column('planet_table', 'sourceofwater')
    op.drop_column('planet_table', 'placement')
    op.drop_column('planet_table', 'replacedtree')
    op.drop_column('planet_table', 'energysource')
    op.drop_column('planet_table', 'mill')
    op.drop_column('planet_table', 'burning')
    op.drop_column('planet_table', 'disaster')
    op.drop_column('planet_table', 'season')
    op.drop_column('planet_table', 'croprotation')
    op.drop_column('planet_table', 'degradedland')
    op.drop_column('planet_table', 'qtybought')
    op.drop_column('planet_table', 'seedlingprice')
    op.drop_column('planet_table', 'buywhere')
    op.drop_column('planet_table', 'raiseorbuy')
    op.drop_column('planet_table', 'variety')
    op.drop_column('planet_table', 'crop')
    op.drop_column('planet_table', 'plantoexpand')
    op.add_column('mobile_data_table', sa.Column('Avweeklydatarefill', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('AvTimeSpentOnApp', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('MobilePhoneType', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('MobileAppKinds', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('NoOfmobileapps', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('Dataprecedingplanswitch', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('Callsoutminutes', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('Callsoutnumber', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('Avweeklyphoneuse', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('Callsinnumber', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('SMSsent', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('Callinminutes', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('AppDeleteRate', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mobile_data_table', sa.Column('Billpaymenthistory', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('mobile_data_table', 'appdeleterate')
    op.drop_column('mobile_data_table', 'mobileappkinds')
    op.drop_column('mobile_data_table', 'avtimespentonapp')
    op.drop_column('mobile_data_table', 'noOfmobileapps')
    op.drop_column('mobile_data_table', 'avweeklydatarefill')
    op.drop_column('mobile_data_table', 'billpaymenthistory')
    op.drop_column('mobile_data_table', 'dataprecedingplanswitch')
    op.drop_column('mobile_data_table', 'smssent')
    op.drop_column('mobile_data_table', 'callinminutes')
    op.drop_column('mobile_data_table', 'callsinnumber')
    op.drop_column('mobile_data_table', 'callsoutminutes')
    op.drop_column('mobile_data_table', 'callsoutnumber')
    op.drop_column('mobile_data_table', 'avweeklyphoneuse')
    op.drop_column('mobile_data_table', 'mobilephonetype')
    op.add_column('mechanization_table', sa.Column('MachineHasHelped', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('OtherMachinesNeeded', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('CanAcquireMoreLands', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('PercentCostSaved', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('AdviseMachineOrLabour', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('mechanization_table', sa.Column('MachinesUsed', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('mechanization_table', 'percentcostsaved')
    op.drop_column('mechanization_table', 'canacquiremorelands')
    op.drop_column('mechanization_table', 'othermachinesneeded')
    op.drop_column('mechanization_table', 'advisemachineorlabour')
    op.drop_column('mechanization_table', 'machinehashelped')
    op.drop_column('mechanization_table', 'machinesused')
    op.drop_constraint(None, 'loantransfers', type_='unique')
    op.add_column('living_table', sa.Column('StandardofLiving', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('KitchenSink', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('LivesWith', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('HasAccessedInput', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('HouseHoldEats', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('FemaleAboveAge', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('RelationshipWithOwner', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('HaveElectricity', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('FemaleUnderAge', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('CookingMethod', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('ChildrenUnderAge', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('MaleAboveAge', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('ChildrenAboveAge', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('OwnOtherLands', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('HasGroup', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('SourceEverytime', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('PowerPayment', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('Input', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('SourceOfWater', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('HouseOwned', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('MaleUnderAge', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('Typeoftoilet', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('StaysWithFamily', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('living_table', sa.Column('Position', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('living_table', 'input')
    op.drop_column('living_table', 'hasaccessedInput')
    op.drop_column('living_table', 'position')
    op.drop_column('living_table', 'hasgroup')
    op.drop_column('living_table', 'kitchensink')
    op.drop_column('living_table', 'typeoftoilet')
    op.drop_column('living_table', 'powerpayment')
    op.drop_column('living_table', 'haveelectricity')
    op.drop_column('living_table', 'cookingmethod')
    op.drop_column('living_table', 'sourceeverytime')
    op.drop_column('living_table', 'sourceofwater')
    op.drop_column('living_table', 'standardofliving')
    op.drop_column('living_table', 'ownotherlands')
    op.drop_column('living_table', 'liveswith')
    op.drop_column('living_table', 'childrenaboveage')
    op.drop_column('living_table', 'femaleaboveage')
    op.drop_column('living_table', 'maleaboveage')
    op.drop_column('living_table', 'childrenunderage')
    op.drop_column('living_table', 'femaleunderage')
    op.drop_column('living_table', 'maleunderage')
    op.drop_column('living_table', 'householdeats')
    op.drop_column('living_table', 'relationshipwithowner')
    op.drop_column('living_table', 'stayswithfamily')
    op.drop_column('living_table', 'houseowned')
    op.add_column('inputs_info', sa.Column('Herbicides', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('Fertilizers', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('Fungicides', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('Insecticides', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('inputs_info', sa.Column('Seeds', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('inputs_info', 'seeds')
    op.drop_column('inputs_info', 'insecticides')
    op.drop_column('inputs_info', 'fungicides')
    op.drop_column('inputs_info', 'herbicides')
    op.drop_column('inputs_info', 'fertilizers')
    op.add_column('farmland_table', sa.Column('FarmAddress', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('NoOfFarmlands', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('FarmCoordinates', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('InheritedFrom', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('OwnerOrCaretaker', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('FarmOwnerPhoneNo', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('FarmOwnerName', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('AnimalsFeedOn', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('RelationshipWithOwner', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('KeepsAnimals', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farmland_table', sa.Column('SizeOfFarm', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('farmland_table', 'animalsfeedon')
    op.drop_column('farmland_table', 'keepsanimals')
    op.drop_column('farmland_table', 'farmaddress')
    op.drop_column('farmland_table', 'farmcoordinates')
    op.drop_column('farmland_table', 'sizeoffarm')
    op.drop_column('farmland_table', 'inheritedfrom')
    op.drop_column('farmland_table', 'relationshipwithowner')
    op.drop_column('farmland_table', 'farmownerphoneno')
    op.drop_column('farmland_table', 'farmownername')
    op.drop_column('farmland_table', 'ownerorcaretaker')
    op.drop_column('farmland_table', 'nooffarmlands')
    op.drop_constraint(None, 'farmer_table', type_='unique')
    op.add_column('farm_practice_table', sa.Column('ApproxFertilizerUse', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('UsesMachines', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('NoOfHectaresProducedYearly', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('CropthatcanSellWell', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('WeedControlPractice', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('NoOfYearsLeased', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('RotatesCrops', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('NoOfFertlizerApplications', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('HasFarmPlanOrProject', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('DecisionForSpraying', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('FarmIsRentedorLeased', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('FarmProjectInfo', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('EstimatedIncomePerCrop', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('farm_practice_table', sa.Column('SizeOfFarm', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('farm_practice_table', 'farmprojectinfo')
    op.drop_column('farm_practice_table', 'hasfarmplanorproject')
    op.drop_column('farm_practice_table', 'cropthatcansellwell')
    op.drop_column('farm_practice_table', 'estimatedincomepercrop')
    op.drop_column('farm_practice_table', 'weedcontrolpractice')
    op.drop_column('farm_practice_table', 'decisionforspraying')
    op.drop_column('farm_practice_table', 'nooffertlizerapplications')
    op.drop_column('farm_practice_table', 'approxfertilizeruse')
    op.drop_column('farm_practice_table', 'noOfhectaresproducedyearly')
    op.drop_column('farm_practice_table', 'rotatescrops')
    op.drop_column('farm_practice_table', 'usesmachines')
    op.drop_column('farm_practice_table', 'noofyearsleased')
    op.drop_column('farm_practice_table', 'farmisrentedorleased')
    op.drop_column('farm_practice_table', 'sizeoffarm')
    op.add_column('credit_history_table', sa.Column('CanProvideCollateral', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('WhyNoCollateral', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('HowLoanWasRepaid', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('HasTakenLoanBefore', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('PastLoanAmount', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('SourceOfLoan', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_history_table', sa.Column('IsReadyToPayInterest', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('credit_history_table', 'whynocollateral')
    op.drop_column('credit_history_table', 'canprovidecollateral')
    op.drop_column('credit_history_table', 'isreadytopayinterest')
    op.drop_column('credit_history_table', 'howloanwasrepaid')
    op.drop_column('credit_history_table', 'pastloanamount')
    op.drop_column('credit_history_table', 'sourceofloan')
    op.drop_column('credit_history_table', 'hastakenloanbefore')
    op.add_column('credit_access_table', sa.Column('ApplyLoanAmount', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('DifficultyReason', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('EstMonthlyIncome', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('NoOfRepaidLoans', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('SavingsAmount', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('DifficultLoanAmount', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('HasServedAsTreasurer', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('NoOfTimesExchanged', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('FarmProduceExchanged', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('DurationAsTreasurer', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('NoOfDifficultLoans', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('Collateral', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('SavesMoneyMonthly', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('NoOfLoansOnTime', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('AnnualTurnover', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('CostOfCultivation', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('HadDifficultyRepaying', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('credit_access_table', sa.Column('YearsOfCultivating', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('credit_access_table', 'annualturnover')
    op.drop_column('credit_access_table', 'yearsofcultivating')
    op.drop_column('credit_access_table', 'applyloanamount')
    op.drop_column('credit_access_table', 'collateral')
    op.drop_column('credit_access_table', 'nooftimesexchanged')
    op.drop_column('credit_access_table', 'farmproduceexchanged')
    op.drop_column('credit_access_table', 'costofcultivation')
    op.drop_column('credit_access_table', 'estmonthlyincome')
    op.drop_column('credit_access_table', 'noofloansontime')
    op.drop_column('credit_access_table', 'noofrepaidloans')
    op.drop_column('credit_access_table', 'noofdifficultloans')
    op.drop_column('credit_access_table', 'difficultyreason')
    op.drop_column('credit_access_table', 'difficultloanamount')
    op.drop_column('credit_access_table', 'haddifficultyrepaying')
    op.drop_column('credit_access_table', 'savingsamount')
    op.drop_column('credit_access_table', 'savesmoneymonthly')
    op.drop_column('credit_access_table', 'durationastreasurer')
    op.drop_column('credit_access_table', 'hasservedastreasurer')
    op.add_column('conditions_table', sa.Column('ZowaselMarketplacePriceOffers', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('conditions_table', sa.Column('CropExpectedMarketValue', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('conditions_table', sa.Column('CropYieldPrediction', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('conditions_table', 'zowaselmarketplacepriceoffers')
    op.drop_column('conditions_table', 'cropexpectedmarketvalue')
    op.drop_column('conditions_table', 'cropyieldprediction')
    op.add_column('care_table', sa.Column('HealthCentDistance', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('InjuryEvent', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('FirstAid', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('Level', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('StudyWhere', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('SchoolCount', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('AltIncomeSource', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('LastCheck', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('StudyTime', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('SchoolFunctional', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('HealthCentFunctional', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('HealthCentLoc', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('HealthCentCount', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('InSchool', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('FarmDistance', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('Qualification', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('care_table', sa.Column('Affordable', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('care_table', 'altIncomesource')
    op.drop_column('care_table', 'studywhere')
    op.drop_column('care_table', 'studytime')
    op.drop_column('care_table', 'qualification')
    op.drop_column('care_table', 'schoolfunctional')
    op.drop_column('care_table', 'schoolcount')
    op.drop_column('care_table', 'level')
    op.drop_column('care_table', 'inschool')
    op.drop_column('care_table', 'lastcheck')
    op.drop_column('care_table', 'firstaid')
    op.drop_column('care_table', 'injuryevent')
    op.drop_column('care_table', 'farmdistance')
    op.drop_column('care_table', 'affordable')
    op.drop_column('care_table', 'healthcentfunctional')
    op.drop_column('care_table', 'healthcentdistance')
    op.drop_column('care_table', 'healthcentcount')
    op.drop_column('care_table', 'healthcentloc')
    op.add_column('capital_table', sa.Column('OtherIncomeSource', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('FirstFundingOption', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('PayBackMonths', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('NoOfIncomeEarners', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('PestExpenseChanged', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('MainIncomeSource', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('HarvestQtyChanged', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('HasBankAccount', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capital_table', sa.Column('NeedsALoan', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('capital_table', 'pestexpensechanged')
    op.drop_column('capital_table', 'harvestqtychanged')
    op.drop_column('capital_table', 'paybackmonths')
    op.drop_column('capital_table', 'needsaloan')
    op.drop_column('capital_table', 'firstfundingoption')
    op.drop_column('capital_table', 'hasbankaccount')
    op.drop_column('capital_table', 'noofincomeearners')
    op.drop_column('capital_table', 'otherincomesource')
    op.drop_column('capital_table', 'mainincomesource')
    op.add_column('capacity_table', sa.Column('HasCooperative', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('EducationLevel', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('CooperativeName', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('FarmingPractice', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('ParticipatedInTraining', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('HowLongBeenFarming', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('capacity_table', sa.Column('KeepsAnimals', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('capacity_table', 'educationlevel')
    op.drop_column('capacity_table', 'cooperativename')
    op.drop_column('capacity_table', 'hascooperative')
    op.drop_column('capacity_table', 'keepsanimals')
    op.drop_column('capacity_table', 'farmingpractice')
    op.drop_column('capacity_table', 'participatedintraining')
    op.drop_column('capacity_table', 'howlongbeenfarming')
    op.add_column('agronomy_services_table', sa.Column('RecordKeepingBenefits', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('CanManageEcosystem', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('KnowsAgriProcessed', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('HowToManageEcosystem', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('HarvestingChanges', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('CropCalendarBenefits', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('IsCropCalendarBeneficial', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('FieldRoutines', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('IsTrainingBeneficial', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('agronomy_services_table', sa.Column('AgronomistThatTrainedYou', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('agronomy_services_table', 'recordkeepingbenefits')
    op.drop_column('agronomy_services_table', 'cropcalendarbenefits')
    op.drop_column('agronomy_services_table', 'iscropcalendarbeneficial')
    op.drop_column('agronomy_services_table', 'harvestingchanges')
    op.drop_column('agronomy_services_table', 'fieldroutines')
    op.drop_column('agronomy_services_table', 'istrainingbeneficial')
    op.drop_column('agronomy_services_table', 'howtomanageecosystem')
    op.drop_column('agronomy_services_table', 'canmanageecosystem')
    op.drop_column('agronomy_services_table', 'agronomistthattrainedyou')
    op.drop_column('agronomy_services_table', 'knowsagriprocessed')
    # ### end Alembic commands ###
