"""empty message

Revision ID: 7ba98faa2a32
Revises: ae27e2079252
Create Date: 2022-11-25 07:14:13.531520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ba98faa2a32'
down_revision = 'ae27e2079252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer_table', sa.Column('farmer_id', sa.String(length=200), nullable=True))
    op.drop_index('uuid', table_name='farmer_table')
    op.create_unique_constraint(None, 'farmer_table', ['farmer_id'])
    op.drop_column('farmer_table', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer_table', sa.Column('uuid', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'farmer_table', type_='unique')
    op.create_index('uuid', 'farmer_table', ['uuid'], unique=False)
    op.drop_column('farmer_table', 'farmer_id')
    # ### end Alembic commands ###
