"""empty message

Revision ID: 8beaa9ffa7ef
Revises: 47a5b9574cd4
Create Date: 2022-11-16 07:50:23.619643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8beaa9ffa7ef'
down_revision = '47a5b9574cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='agronomy_services_table')
    op.drop_table('agronomy_services_table')
    op.drop_index('Bvn', table_name='score_card')
    op.drop_index('id', table_name='score_card')
    op.drop_table('score_card')
    op.drop_index('id', table_name='capital_table')
    op.drop_table('capital_table')
    op.drop_index('id', table_name='credit_history_table')
    op.drop_table('credit_history_table')
    op.drop_index('id', table_name='capacity_table')
    op.drop_table('capacity_table')
    op.drop_index('id', table_name='farmer_table')
    op.drop_table('farmer_table')
    op.drop_index('id', table_name='movement_table')
    op.drop_table('movement_table')
    op.drop_index('id', table_name='living_table')
    op.drop_table('living_table')
    op.drop_index('tracing_id', table_name='crop_quality')
    op.drop_table('crop_quality')
    op.drop_table('products')
    op.drop_index('id', table_name='harvest_table')
    op.drop_table('harvest_table')
    op.drop_index('id', table_name='care_table')
    op.drop_table('care_table')
    op.drop_index('id', table_name='mobile_data_table')
    op.drop_table('mobile_data_table')
    op.drop_index('id', table_name='farm_practice_table')
    op.drop_table('farm_practice_table')
    op.drop_table('loans')
    op.drop_index('tracing_id', table_name='crop_info')
    op.drop_table('crop_info')
    op.drop_table('loantransfers')
    op.drop_index('id', table_name='productivity_viability_table')
    op.drop_table('productivity_viability_table')
    op.drop_index('id', table_name='planet_table')
    op.drop_table('planet_table')
    op.drop_index('id', table_name='mechanization_table')
    op.drop_table('mechanization_table')
    op.drop_index('id', table_name='cultivation_table')
    op.drop_table('cultivation_table')
    op.drop_index('id', table_name='conditions_table')
    op.drop_table('conditions_table')
    op.drop_index('tracing_id', table_name='shipment_table')
    op.drop_table('shipment_table')
    op.drop_table('locations')
    op.drop_index('id', table_name='farmland_table')
    op.drop_table('farmland_table')
    op.drop_index('tracing_id', table_name='recommendation_table')
    op.drop_table('recommendation_table')
    op.drop_index('tracing_id', table_name='warehouse_table')
    op.drop_table('warehouse_table')
    op.drop_index('id', table_name='safety_table')
    op.drop_table('safety_table')
    op.drop_index('id', table_name='credit_access_table')
    op.drop_table('credit_access_table')
    op.drop_index('id', table_name='psychometrics_table')
    op.drop_table('psychometrics_table')
    op.drop_table('crops')
    op.drop_index('tracing_id', table_name='inputs_info')
    op.drop_table('inputs_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputs_info',
    sa.Column('tracing_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Fertilizers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Herbicides', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Fungicides', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Insecticides', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Seeds', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tracing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tracing_id', 'inputs_info', ['tracing_id'], unique=False)
    op.create_table('crops',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('crop_name', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('variety', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('farmer_name', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('cost_price', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('selling_price', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('psychometrics_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FluidIntelligence', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AttitudesandBeliefs', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AgribusinessSkills', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EthicsandHonesty', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SavesEnough', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasLazyNeighbors', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'psychometrics_table', ['id'], unique=False)
    op.create_table('credit_access_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasServedAsTreasurer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DurationAsTreasurer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SavesMoneyMonthly', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SavingsAmount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HadDifficultyRepaying', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DifficultLoanAmount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DifficultyReason', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfDifficultLoans', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfRepaidLoans', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfLoansOnTime', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EstMonthlyIncome', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CostOfCultivation', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmProduceExchanged', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfTimesExchanged', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Collateral', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ApplyLoanAmount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('YearsOfCultivating', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AnnualTurnover', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'credit_access_table', ['id'], unique=False)
    op.create_table('safety_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Ferment', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FermentDays', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FermentReason', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('BrokenQty', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DoWithBroken', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('UnripeQty', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DoWithUnripe', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CocoaStore', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FFBStore', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Herbicide', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HerbicideStore', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AgroChemSource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HarvestTool', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Wear', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Disposal', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'safety_table', ['id'], unique=False)
    op.create_table('warehouse_table',
    sa.Column('tracing_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('warehouse_type', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('capacity', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('standard', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('insurance', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('duration', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('cost', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tracing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tracing_id', 'warehouse_table', ['tracing_id'], unique=False)
    op.create_table('recommendation_table',
    sa.Column('tracing_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('rec_one', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('rec_two', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('rec_three', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tracing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tracing_id', 'recommendation_table', ['tracing_id'], unique=False)
    op.create_table('farmland_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfFarmlands', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OwnerOrCaretaker', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmOwnerName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmOwnerPhoneNo', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RelationshipWithOwner', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('InheritedFrom', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SizeOfFarm', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmCoordinates', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmAddress', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('KeepsAnimals', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AnimalsFeedOn', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farmland_table', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('shipment_table',
    sa.Column('tracing_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('loading_date', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_people', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('vehicle_type', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('plate_no', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('vehicle_capacity', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('driver_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('driver_number', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('insurance', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('delivery_time', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('delivery_date', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('arrival_time', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_police', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('local_levy', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('state_levy', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('truck_levy', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('inter_state_levy', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_offloaders', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('quality_check', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('quality_checked', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('quality_accepted', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('quality_rejected', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tracing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tracing_id', 'shipment_table', ['tracing_id'], unique=False)
    op.create_table('conditions_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('LengthOfHarvestChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'conditions_table', ['id'], unique=False)
    op.create_table('cultivation_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('type_of_labor', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pay_for_labor', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('how_many_housechildren_help', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('season_children_help', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('labor_children_do', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('household_vs_hire_cost', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('labor_women_do', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('percent_female_hired', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'cultivation_table', ['id'], unique=False)
    op.create_table('mechanization_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MachinesUsed', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MachineHasHelped', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AdviseMachineOrLabour', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OtherMachinesNeeded', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CanAcquireMoreLands', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PercentCostSaved', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'mechanization_table', ['id'], unique=False)
    op.create_table('planet_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PlanToExpand', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Crop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Variety', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RaiseOrBuy', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('BuyWhere', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SeedlingPrice', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('QtyBought', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DegradedLand', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropRotation', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Season', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Disaster', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Burning', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Mill', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EnergySource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ReplacedTree', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Placement', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SourceOfWater', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CoverCrops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Intercrop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropIntercropped', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WasteMgt', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WasteDisposal', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RecycleWaste', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Suffered', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WhenSuffered', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('GreyWater', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RecycleGreyWater', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Pollution', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PollutionFreq', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Measures', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'planet_table', ['id'], unique=False)
    op.create_table('productivity_viability_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropsCultivated', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('GrowsCrops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OilPalmFertilizers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CocoaFertilizers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FertilizerFrequency', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PestFungHerbicides', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('StageChemicalApplied', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfOilDrums', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfBagsSesame', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfBagsSoyaBeans', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfBagsMaize', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfBagsSorghum', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfBagsCocoaBeans', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropTrainedOn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WhereWhenWhoTrained', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfTraining', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PruningFrequency', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropBasedProblems', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('TooYoungCrops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('YoungCropsAndStage', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CultivationStartdate', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsIntensiveFarmingPractised', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EconomicActivities', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'productivity_viability_table', ['id'], unique=False)
    op.create_table('loantransfers',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('loan_type', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('amount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('to_farmer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('farmer_contact', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('transfer_time', mysql.DATETIME(), nullable=True),
    sa.Column('due_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('crop_info',
    sa.Column('tracing_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('crop_type', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('sourcing_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('crop_origin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('crop_qty', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('crop_variety', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('cooperative', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_farmer_group', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('female_to_male', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('farmer_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tracing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tracing_id', 'crop_info', ['tracing_id'], unique=False)
    op.create_table('loans',
    sa.Column('loan_type', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('loan_type'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('farm_practice_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SizeOfFarm', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmIsRentedorLeased', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfYearsLeased', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('UsesMachines', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RotatesCrops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfHectaresProducedYearly', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ApproxFertilizerUse', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfFertlizerApplications', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DecisionForSpraying', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WeedControlPractice', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EstimatedIncomePerCrop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropthatcanSellWell', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasFarmPlanOrProject', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmProjectInfo', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farm_practice_table', ['id'], unique=False)
    op.create_table('mobile_data_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MobilePhoneType', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Avweeklyphoneuse', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Callsoutnumber', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Callsoutminutes', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Callsinnumber', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Callinminutes', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SMSsent', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Dataprecedingplanswitch', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Billpaymenthistory', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Avweeklydatarefill', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfmobileapps', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AvTimeSpentOnApp', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MobileAppKinds', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AppDeleteRate', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'mobile_data_table', ['id'], unique=False)
    op.create_table('care_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HealthCentLoc', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HealthCentCount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HealthCentDistance', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HealthCentFunctional', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Affordable', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmDistance', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('InjuryEvent', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FirstAid', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('LastCheck', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('InSchool', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Level', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SchoolCount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SchoolFunctional', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Qualification', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('StudyTime', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('StudyWhere', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AltIncomeSource', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'care_table', ['id'], unique=False)
    op.create_table('harvest_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('when_is_harvest_season', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_hired_workers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_family_workers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_permanent_workers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_hired_constantly', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'harvest_table', ['id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('crop_quality',
    sa.Column('tracing_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('moisture_content', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('foreign_matter', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('test_weight', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('quality', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('rotten_shriveled', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('hardness', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('splits', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('oil_content', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('infestation', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('hectoliter', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('total_defects', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('dockage', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ash_content', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('insoluble_ash', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('volatile', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('mold_weight', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('drying_process', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('dead_insects', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('excreta', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('insect_defiled', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('curcumin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('extraneous', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tracing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tracing_id', 'crop_quality', ['tracing_id'], unique=False)
    op.create_table('living_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HouseOwned', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('StaysWithFamily', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RelationshipWithOwner', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HouseHoldEats', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MaleUnderAge', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FemaleUnderAge', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ChildrenUnderAge', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MaleAboveAge', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FemaleAboveAge', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ChildrenAboveAge', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('LivesWith', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OwnOtherLands', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('StandardofLiving', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SourceOfWater', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SourceEverytime', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CookingMethod', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HaveElectricity', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PowerPayment', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Typeoftoilet', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('KitchenSink', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasGroup', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Group', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Position', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasAccessedInput', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Input', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'living_table', ['id'], unique=False)
    op.create_table('movement_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('product', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('from_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('to_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('movement_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'movement_table', ['id'], unique=False)
    op.create_table('farmer_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Surname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Middlename', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Telephone', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Age', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Gender', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Language', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MaritalStatus', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Bankname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Accountno', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MeansofID', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Issuedate', mysql.DATETIME(), nullable=True),
    sa.Column('Expirydate', mysql.DATETIME(), nullable=True),
    sa.Column('Nin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PermanentAddress', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Landmark', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Stateoforigin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsinaGroup', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ReasonNoGroup', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Group', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NumberofMembers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FirstNameNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SurnameNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MiddlenameNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RelationshipNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OccupationNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('TelephoneNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PermanentAddressNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('LandmarkNok', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NinNok', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farmer_table', ['id'], unique=False)
    op.create_table('capacity_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowLongBeenFarming', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ParticipatedInTraining', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FarmingPractice', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('KeepsAnimals', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasCooperative', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CooperativeName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EducationLevel', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'capacity_table', ['id'], unique=False)
    op.create_table('credit_history_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasTakenLoanBefore', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SourceOfLoan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PastLoanAmount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowLoanWasRepaid', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsReadyToPayInterest', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CanProvideCollateral', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WhyNoCollateral', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'credit_history_table', ['id'], unique=False)
    op.create_table('capital_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MainIncomeSource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OtherIncomeSource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfIncomeEarners', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HasBankAccount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FirstFundingOption', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NeedsALoan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PayBackMonths', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HarvestQtyChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PestExpenseChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'capital_table', ['id'], unique=False)
    op.create_table('score_card',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('age', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('number_of_land', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('owner_caretaker', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('crop', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('intercropping', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('machines', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('estimate_monthly_income', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('years_cultivating', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('owns_a_bank_account', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('size_of_farm', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('number_of_crops', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_in_a_cooperative', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('no_of_agronomist_visits', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'score_card', ['id'], unique=False)
    op.create_index('Bvn', 'score_card', ['Bvn'], unique=False)
    op.create_table('agronomy_services_table',
    sa.Column('id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Bvn', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('KnowsAgriProcessed', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AgronomistThatTrainedYou', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CanManageEcosystem', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HowToManageEcosystem', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsTrainingBeneficial', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FieldRoutines', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('HarvestingChanges', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('IsCropCalendarBeneficial', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('CropCalendarBenefits', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('RecordKeepingBenefits', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'agronomy_services_table', ['id'], unique=False)
    # ### end Alembic commands ###
