"""empty message

Revision ID: a76aa0d02878
Revises: f116c2705a33
Create Date: 2023-01-06 18:37:40.391175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76aa0d02878'
down_revision = 'f116c2705a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loantransfers', sa.Column('repayment_months', sa.String(length=200), nullable=True))
    op.add_column('loantransfers', sa.Column('repaid', sa.String(length=200), nullable=True))
    op.add_column('loantransfers', sa.Column('balance', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loantransfers', 'balance')
    op.drop_column('loantransfers', 'repaid')
    op.drop_column('loantransfers', 'repayment_months')
    # ### end Alembic commands ###
