"""empty message

Revision ID: ae27e2079252
Revises: cd7aae11114d
Create Date: 2022-11-25 07:06:20.819282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae27e2079252'
down_revision = 'cd7aae11114d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer_table', sa.Column('uuid', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'farmer_table', ['uuid'])
    op.create_unique_constraint(None, 'loans', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='unique')
    op.drop_constraint(None, 'farmer_table', type_='unique')
    op.drop_column('farmer_table', 'uuid')
    # ### end Alembic commands ###
