"""empty message

Revision ID: cd7aae11114d
Revises: 5491d2dce25a
Create Date: 2022-11-25 06:26:15.661717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7aae11114d'
down_revision = '5491d2dce25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('interest_rate_per_annum', sa.Integer(), nullable=True))
    op.drop_index('id', table_name='loans')
    op.add_column('loantransfers', sa.Column('repayment_amount', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loantransfers', 'repayment_amount')
    op.create_index('id', 'loans', ['id'], unique=False)
    op.drop_column('loans', 'interest_rate_per_annum')
    # ### end Alembic commands ###
