"""empty message

Revision ID: d5d653e1f392
Revises: 2b8a9cb511f8
Create Date: 2022-11-01 18:21:54.837247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5d653e1f392'
down_revision = '2b8a9cb511f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='credit_access_table')
    op.drop_table('credit_access_table')
    op.drop_index('id', table_name='farmer_table')
    op.drop_table('farmer_table')
    op.drop_index('id', table_name='movement_table')
    op.drop_table('movement_table')
    op.drop_index('id', table_name='capital_table')
    op.drop_table('capital_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BVN', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MainIncomeSource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OtherIncomeSource', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfIncomeEarners', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AccountHolder', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FundingOption', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NeedALoan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PayBackMonths', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HarvestQtyChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PestExpenseChanged', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'capital_table', ['id'], unique=False)
    op.create_table('movement_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('to_location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('movement_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'movement_table', ['id'], unique=False)
    op.create_table('farmer_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Surname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Telephone', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Age', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Gender', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('MaritalStatus', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('BVN', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MeansofID', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('YearofIssue', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ExpiryYear', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NIN', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PermanentAddress', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Landmark', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Stateoforigin', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('LGA', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Group', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'farmer_table', ['id'], unique=False)
    op.create_table('credit_access_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BVN', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HasServedAsTreasurer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DurationAsTreasurer', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SavesMoneyMonthly', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('SavingsAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HadDifficultyRepaying', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DifficultLoanAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DifficultyReason', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfDifficultLoans', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfRepaidLoans', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NoOfLoansOnTime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EstMonthlyIncome', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CostOfCultivation', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FarmProduceExchanged', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('NoOfTimesExchanged', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Collateral', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ApplyLoanAmount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('YearsOfCultivating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AnnualTurnover', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'credit_access_table', ['id'], unique=False)
    # ### end Alembic commands ###
